Написана разметка
htmlacademy-htmlcss/2009243-sedona-33 pull request #2
Opened 2022-02-01 07:45 UTC by Hindesert

2022-02-01 16:39 UTC, vladpovelitsa requested changes
Есть мелкие замечания, в целом хорошая работа, молодец!

2022-02-01 16:39 UTC, vladpovelitsa commented on index.html
> +        </a>
на главной логотип не должен перезагружать страницу, удалить `href="index.html"`

2022-02-01 16:39 UTC, vladpovelitsa commented on index.html
> +  </div>
Это всё стоит обернуть в список, блоки даже пронумерованы :)

2022-02-02 07:48 UTC, Hindesert commented on index.html
> +  </div>
T.e <div> стоит заменить на <ol>? c:

2022-02-07 21:26 UTC, vladpovelitsa approved these changes
Принимаю задание, хоть и есть проблемы с форматирование, но к коду вопросов больше нет, молодец!. Я тебе в телеграм напишу как это быстро исправить.

2022-02-07 21:26 UTC, vladpovelitsa commented on index.html
> +      <img class="city-view" src="" alt="Вид города">
поправь форматирование, тут должен быть отступ

2022-02-07 21:26 UTC, vladpovelitsa commented on index.html
> +      <p class="bonus-advantages-description">Рекомендуем пожить<br>в настоящем мотеле,<br>всё как в кино!</p>
форматирование тут и далее по сайту

2022-02-07 21:27 UTC, merged