Добавлены изображения и базовая стилизация
htmlacademy-htmlcss/2009243-sedona-33 pull request #3
Opened 2022-02-18 12:29 UTC by Hindesert

2022-02-22 07:13 UTC, vladpovelitsa requested changes
Посмотрел шапку, в целом у тебя все правильно сделано, дальше по программе у тебя будет создание сеток на flexbox css и grid css и ты сможешь откорректировать расположение элементов. 

В остальном небольшие замечания есть, но не критичные, хорошая работа!

2022-02-22 07:13 UTC, vladpovelitsa commented on styles.css
> +}
поправь форматирование, чтобы все отступы были однородными

2022-02-22 07:13 UTC, vladpovelitsa commented on styles.css
> +}
лучше использовать классы для стилизации

2022-02-22 07:13 UTC, vladpovelitsa commented on index.html
> +    </a>
в html тоже нужно поправить форматирование

2022-02-22 07:13 UTC, vladpovelitsa commented on index.html
>          <ul class="navigation-list navigation-user">
я бы убрал у этого списка класс, чтобы не было проблем в дальнейшем navigation-list

2022-03-11 17:58 UTC, Muhammadabumansur commented on index.html
> +            <img  src="images/search.svg" width="18,05" height="18,01">
Невалидные значения в атрибутах width height, должны быть только числа, без запятых и других символов

2022-03-11 17:58 UTC, Muhammadabumansur commented on index.html
> +            <img  src="images/search.svg" width="18,05" height="18,01">
И у каждой картинки должен быть атрибут alt

2022-03-11 17:58 UTC, Muhammadabumansur commented on index.html
> +            <img  src="images/search.svg" width="18,05" height="18,01">
По этим замечаниям надо исправить весь файл

2022-03-11 17:59 UTC, Muhammadabumansur commented
Таких названий как Vector.png не должно быть, не должно быть заглавных букв и имя должно быть со смыслом. Вообще, этот файл нужно сохранить в svg

2022-03-15 16:36 UTC, Muhammadabumansur commented on index.html
>        <div class="motel">
Непосредственно в ol не может быть div

2022-03-15 16:36 UTC, Muhammadabumansur commented on index.html
>        <div class="meal">
Непосредственно в ol не может быть div

2022-03-15 16:36 UTC, Muhammadabumansur commented on index.html
>        <div class="souvenirs">
Непосредственно в ol не может быть div

2022-03-15 16:36 UTC, Muhammadabumansur commented on index.html
>      </li>
Здесь закрывается li, но нет соответствующего ему открывающего li. Судя по всему, ты пропустила открывающий li на 79 строчке

2022-03-15 16:36 UTC, Muhammadabumansur commented on index.html
>      </li>
Из-за этого все ошибки валидации. Проверяй здесь https://validator.w3.org/nu/ это удобно

2022-03-15 16:36 UTC, Muhammadabumansur commented
Это замечание https://github.com/htmlacademy-htmlcss/2009243-sedona-33/pull/3#issuecomment-1065351184 не исправлено

2022-03-17 17:49 UTC, Muhammadabumansur commented
Все ок. Только удали в корне этот файл

![image](https://user-images.githubusercontent.com/16342548/158864275-75c5add4-9fc2-482f-ad47-5e3ed3d6516a.png)

2022-03-17 17:49 UTC, merged